import { Blinker } from "next/font/google";
import "./globals.css";

const blinker = Blinker(
  { subsets: ["latin"], 
    weight: ["400", "700",'900'], 
    variable: "--font-blinker" });

export const metadata = {
  title: "Apple iphone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${blinker.variable} bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
